title:            Cell Bones
description:      Science. Science. Science. Nerd.
disqus_shortname: cellbones
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
#url: http://localhost:4000
url: http://dgoppenheimer.github.io/oppenheimer-blog
# when testing locally, use bundle exec jekyll serve --baseurl '' 
baseurl: /oppenheimer-blog


# Owner/author information
owner:
  name:           David G. Oppenheimer
  avatar:         avatar.jpg
  bio:            "Associate Professor in the Dept. of Biology at the Univ. of Florida, studying cytoskeleton organization and small molecule inhibitors of protein function."
  email:          dg.oppenheimer@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        cell_biology
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  # google_plus:    117160489661726628682
  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "D.G. Oppenheimer"

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
# google_analytics:   
# google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones 
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    redcarpet
redcarpet: 
  extensions: ["disable_indented_code_blocks", "fenced_code_blocks", "smart", "tables", "no_intra_emphasis", "autolink", "strikethrough", "superscript", "with_toc_data"]

# Excerpt separater
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# http://jekyllrb.com/docs/permalinks/
permalink:   pretty

# Amount of post to show on home page
paginate: 5


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]